### ISSUE TITLE
Discord webhook embed sidebar color does not change.

### ISSUE THREAD

**Issue by yoonh12** [PgBiel/discord-webhooks#1]
![image](https://user-images.githubusercontent.com/62804153/78321992-72d8fc80-75a8-11ea-8e58-b764318d780a.png)

Sidebar color isn't working.

**Comment by PgBiel** [comment]
Thank you for reporting this issue! It should now be fixed

**Comment by yoonh12** [comment]
Why doesn't the white color work?#FFFFFF 보낸 사람: Pg Biel보낸 날짜: 2020년 4월 3일 금요일 오후 2:21받는 사람: PgBiel/discord-webhooks참조: yoonh12; Author제목: Re: [PgBiel/discord-webhooks] Discord webhook embed sidebar color does not change. (#1) Thank you for reporting this issue! It should now be fixed—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yoonh12** [comment]
Why doesn't the white color work?
#FFFFFF

**Comment by PgBiel** [comment]
it's a restricted color for embeds, use something like #FFFFFE

**Comment by yoonh12** [comment]
**Thank you!**
